# Generated by Django 5.0.2 on 2024-05-13 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0004_profile_delete_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
    ]
